name: canon_ccapi
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^8.1.3
  built_collection: ^5.1.1
  http: ^0.13.4
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.10
  flutter_lints: ^1.0.4
  build_runner: ^2.1.7
  built_value_generator: ^8.1.3

# The following section is specific to Flutter.
flutter: